# Three girls

In which we solve the three-girls-in-family problem.

In [1]:
import numpy as np
np.set_printoptions(precision=2)

In [2]:
one_family = np.random.uniform(size=4)
one_family

array([ 0.72,  0.13,  0.7 ,  0.58])

In [3]:
girls = one_family < 0.5
girls

array([False,  True, False, False], dtype=bool)

In [4]:
n_girls = np.count_nonzero(girls)
n_girls

1

In [5]:
ten_families = np.random.uniform(size=(10, 4))
ten_families

array([[ 0.39,  0.03,  0.67,  0.51],
       [ 0.6 ,  0.29,  0.2 ,  0.71],
       [ 0.04,  0.82,  0.46,  1.  ],
       [ 0.51,  0.94,  0.46,  0.15],
       [ 0.48,  0.07,  0.36,  0.99],
       [ 0.45,  0.14,  0.11,  0.56],
       [ 0.33,  0.56,  0.59,  0.63],
       [ 0.63,  0.66,  0.18,  0.5 ],
       [ 0.26,  0.98,  0.37,  0.49],
       [ 0.99,  0.72,  0.76,  0.48]])

In [6]:
are_girls = ten_families < 0.5
are_girls

array([[ True,  True, False, False],
       [False,  True,  True, False],
       [ True, False,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [ True, False,  True,  True],
       [False, False, False,  True]], dtype=bool)

In [7]:
np.count_nonzero(are_girls)

20

In [8]:
n_girls = np.count_nonzero(are_girls, axis=1)
n_girls

array([2, 2, 2, 2, 3, 3, 1, 1, 3, 1])

In [9]:
prop_3 = np.count_nonzero(n_girls == 3) / 10
prop_3

0.3

In [10]:
many_families = np.random.uniform(size=[1000000, 4])
are_girls = many_families < 0.5
n_girls = np.count_nonzero(are_girls, axis=1)
prop_3 = np.count_nonzero(n_girls == 3) / 1000000
prop_3

0.250004